# Generated by Django 5.1.6 on 2026-05-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
