# Generated by Django 5.1.6 on 2026-05-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='single_ride_mode',
            field=models.BooleanField(default=True, help_text='One ride at a time: auto-decline other offers on confirm'),
        ),
    ]
