# Generated by Django 5.1.6 on 2026-05-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_driver_single_ride_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='offered_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Rider's opening price (optional — drivers set prices via offers)", max_digits=10, null=True),
        ),
    ]
