# Generated by Django 5.1.6 on 2026-06-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ride_offered_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['current_latitude', 'current_longitude'], name='driver_lat_lng_idx'),
        ),
    ]
