# Generated by Django 5.1.6 on 2026-06-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_driver_driver_lat_lng_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='offered_price',
        ),
    ]
