# Generated by Django 5.1.6 on 2026-06-19 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_other_vehicle_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rider',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='rider',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RatingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, help_text='Rated or ignored — no longer shown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_requests', to='api.driver')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_requests', to='api.ride')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_requests', to='api.rider')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('ride', 'rider', 'driver')},
            },
        ),
    ]
